language: ruby
dist: trusty
sudo: required
cache: bundler
services:
  - postgresql
  - mysql
bundler_args: --without yard guard benchmarks tools
before_script:
  - psql -c 'create database rom_sql;' -U postgres
  - mysql -u root -e 'create database rom_sql;'
script: "bundle exec rake ci"
rvm:
  - 2.1.10
  - 2.2.5
  - 2.3.1
  - rbx
  - jruby
env:
  global:
    - CODECLIMATE_REPO_TOKEN=03d7f66589572702b12426d2bc71c4de6281a96139e33b335b894264b1f8f0b0
    - JRUBY_OPTS='--dev -J-Xmx1024M'
matrix:
  allow_failures:
    - rvm: rbx
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
addons:
  postgresql: 9.5
  apt:
    packages:
      - mysql-server-5.6
      - mysql-client-core-5.6
      - mysql-client-5.6
