language: ruby
sudo: false
cache: bundler
services:
  - postgresql
  - mysql
bundler_args: --without yard guard benchmarks tools
before_script:
  - psql -c 'create database rom_sql;' -U postgres
  - mysql -e 'create database rom_sql;'
script: "bundle exec rake ci"
rvm:
  - 2.1.9
  - 2.2.5
  - 2.3.1
  - rbx-2
  - jruby-9.0.5.0
  - ruby-head
env:
  global:
    - CODECLIMATE_REPO_TOKEN=03d7f66589572702b12426d2bc71c4de6281a96139e33b335b894264b1f8f0b0
    - JRUBY_OPTS='--dev -J-Xmx1024M'
    - PG_LTE_95='false'
addons:
  postgresql: '9.4'
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  include:
    - rvm: jruby-head
      before_install: gem install bundler --no-ri --no-rdoc
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/39e1225f489f38b0bd09
    on_success: change
    on_failure: always
    on_start: false
